# Generated by Django 3.2.5 on 2021-08-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cer',
            name='activity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cer',
            name='files',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='cer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
