# Generated by Django 3.2.5 on 2021-08-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20210815_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cer',
            name='created',
        ),
        migrations.AddField(
            model_name='cer',
            name='issue_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
